### PR TITLE
Ability to configure key server and home did for rvm gpg_key

### PR DESCRIPTION
**Pull request by lesniakania**
Pull request for the issue https://github.com/fnichol/chef-rvm/issues/299

### CODE REVIEW

**Comment by vala** [comment]
Fixes install when current user is just a sudoer and is not root. Thanks

**Comment by lesniakania** [comment]
So can you merge this :)?

**Comment by dmerrick** [comment]
Yes, please! There's been no activity on this repo in 25 days now.

**Comment by lesniakania** [comment]
@martinisoft, @lukeasrodgers, @nomadium - can one of you merge it please?

**Comment by lesniakania** [comment]
Thanks!

**Pull request merged**
